-- ==================================================================
-- MySQL DB Initialization Script for Electricity Monitoring App (EB)
-- Schema includes: roles, users, electricity_usage, bills, notifications
-- Author: Generated by AI (2024)
-- ==================================================================

-- 1. Table: roles
--    Stores user roles (e.g., 'officer', 'customer')
CREATE TABLE IF NOT EXISTS roles (
    role_id     INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key for roles table.',
    name        VARCHAR(50) NOT NULL UNIQUE COMMENT 'Role name, e.g. officer/customer.',
    description VARCHAR(255) COMMENT 'Optional human-readable description.'
) ENGINE=InnoDB COMMENT='User roles (officer, customer, etc.).';

-- 2. Table: users
--    Stores information for EB officers and customers
CREATE TABLE IF NOT EXISTS users (
    user_id     INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key for users table.',
    username    VARCHAR(50) NOT NULL UNIQUE COMMENT 'Unique user login name.',
    email       VARCHAR(100) NOT NULL UNIQUE COMMENT 'Unique user email.',
    password    VARCHAR(255) NOT NULL COMMENT 'Password hash.',
    full_name   VARCHAR(100) COMMENT 'Full name of the user.',
    role_id     INT NOT NULL COMMENT 'Foreign key to roles table.',
    is_active   BOOLEAN NOT NULL DEFAULT true COMMENT 'Whether user is active.',
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Account creation datetime.',
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles(role_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB COMMENT='EB officers and customers.';

-- Index for fast user lookup by role
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);

-- 3. Table: electricity_usage
--    Each record corresponds to a usage reading for a customer
CREATE TABLE IF NOT EXISTS electricity_usage (
    usage_id        INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key for usage record.',
    user_id         INT NOT NULL COMMENT 'Customer user_id (foreign key).',
    reading_date    DATE NOT NULL COMMENT 'Date of meter reading.',
    reading_value   DECIMAL(10, 2) NOT NULL COMMENT 'Meter reading value in KWh.',
    input_by        INT NOT NULL COMMENT 'Officer user_id who entered this reading.',
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Entry creation datetime.',
    CONSTRAINT fk_usage_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_input_by_officer
        FOREIGN KEY (input_by) REFERENCES users(user_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB COMMENT='Records of electricity usage entered by officers for customers.';

-- Indexes for efficient query by user and date
CREATE INDEX IF NOT EXISTS idx_usage_user_date ON electricity_usage (user_id, reading_date);
CREATE INDEX IF NOT EXISTS idx_usage_input_by ON electricity_usage (input_by);

-- 4. Table: bills
--    Bill information generated for each usage period for customers
CREATE TABLE IF NOT EXISTS bills (
    bill_id         INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key for bill.',
    user_id         INT NOT NULL COMMENT 'Customer user_id (foreign key).',
    usage_id        INT NOT NULL COMMENT 'Related usage record.',
    amount          DECIMAL(10,2) NOT NULL COMMENT 'Total amount for this bill.',
    due_date        DATE NOT NULL COMMENT 'Payment due date.',
    status          ENUM('unpaid', 'paid', 'overdue') DEFAULT 'unpaid' COMMENT 'Bill payment status.',
    generated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Datetime bill was generated.',
    paid_at         DATETIME DEFAULT NULL COMMENT 'Datetime bill was paid.',
    CONSTRAINT fk_bill_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_bill_usage
        FOREIGN KEY (usage_id) REFERENCES electricity_usage(usage_id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB COMMENT='Electricity bills for each usage record.';

-- Index for quick access to user bills and billing status
CREATE INDEX IF NOT EXISTS idx_bills_user_id ON bills (user_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON bills (status);

-- 5. Table: notifications
--    Tracks all notifications sent to users (including type)
CREATE TABLE IF NOT EXISTS notifications (
    notification_id INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key for notification.',
    user_id         INT NOT NULL COMMENT 'Recipient user_id (foreign key).',
    message         TEXT NOT NULL COMMENT 'Notification content/message.',
    type            ENUM('payment_due', 'bill_paid', 'general', 'alert') NOT NULL DEFAULT 'general' COMMENT 'Type of notification.',
    is_read         BOOLEAN NOT NULL DEFAULT false COMMENT 'Whether notification has been read.',
    sent_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Notification sent timestamp.',
    CONSTRAINT fk_notification_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB COMMENT='Notification log for all users.';

-- Index for fast lookup of unread notifications
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications (user_id, is_read);

-- ==================================================================
-- End of schema. For upgrade scripts, review app version requirements.
-- ==================================================================
